alch_reward = {
	"[Alchemy] Small Delivery Gift Box": {
		"items": {
			"Loggia Alchemist's Clothes": {"rate": 1, "count": 1},
			"Advanced Alchemy Tool": {"rate": 50, "count": 1},
			"Intermediate Alchemy Tool": {"rate": 10, "count": 1},
			"Trace of Chaos": {"rate": 100, "count": 1},
			"Trace of the Earth": {"rate": 100, "count": 1},
			"Trace of Ascension": {"rate": 100, "count": 1},
			"Trace of Savagery": {"rate": 100, "count": 1},
			"Trace of Origin": {"rate": 100, "count": 1},
			"Trace of Battle": {"rate": 100, "count": 1},
			"Trace of Hunting": {"rate": 100, "count": 1},
			"Trace of Forest": {"rate": 100, "count": 1},
			"Trace of Violence": {"rate": 100, "count": 1},
			"Trace of Death": {"rate": 100, "count": 1},
			"Trace of Memory": {"rate": 100, "count": 1},
			"Clear Liquid Reagent": {"rate": 100, "count": 15},
			"Pure Powder Reagent": {"rate": 100, "count": 15},
		}
	},
	"[Alchemy] Plain Delivery Gift Box": {
		"items": {
			"Loggia Alchemist's Clothes": {"rate": 1, "count": 1},
			"Advanced Alchemy Tool": {"rate": 50, "count": 1},
			"Intermediate Alchemy Tool": {"rate": 10, "count": 1},
			"Trace of Chaos": {"rate": 100, "count": 2},
			"Trace of the Earth": {"rate": 100, "count": 2},
			"Trace of Ascension": {"rate": 100, "count": 2},
			"Trace of Savagery": {"rate": 100, "count": 2},
			"Trace of Origin": {"rate": 100, "count": 2},
			"Trace of Battle": {"rate": 100, "count": 2},
			"Trace of Hunting": {"rate": 100, "count": 2},
			"Trace of Forest": {"rate": 100, "count": 2},
			"Trace of Violence": {"rate": 100, "count": 2},
			"Trace of Death": {"rate": 100, "count": 2},
			"Trace of Memory": {"rate": 100, "count": 2},
			"Clear Liquid Reagent": {"rate": 100, "count": 20},
			"Pure Powder Reagent": {"rate": 100, "count": 20},
		}
	},
	"[Alchemy] Resplendent Delivery Gift Box": {
		"items": {
			"Gorgath Alchemist's Clothes": {"rate": 1, "count": 1},
			"Blue Whale Oil": {"rate": 10, "count": 1},
			"Advanced Alchemy Tool": {"rate": 50, "count": 1},
			"Trace of Chaos": {"rate": 100, "count": 3},
			"Trace of the Earth": {"rate": 100, "count": 3},
			"Trace of Ascension": {"rate": 100, "count": 3},
			"Trace of Savagery": {"rate": 100, "count": 3},
			"Trace of Origin": {"rate": 100, "count": 3},
			"Trace of Battle": {"rate": 100, "count": 3},
			"Trace of Hunting": {"rate": 100, "count": 3},
			"Trace of Forest": {"rate": 100, "count": 3},
			"Trace of Violence": {"rate": 100, "count": 3},
			"Trace of Death": {"rate": 100, "count": 3},
			"Trace of Memory": {"rate": 100, "count": 3},
			"Clear Liquid Reagent": {"rate": 100, "count": 25},
			"Pure Powder Reagent": {"rate": 100, "count": 25},
		}
	},
	"[Alchemy] Splendid Delivery Gift Box": {
		"items": {
			"Gorgath Alchemist's Clothes": {"rate": 1, "count": 1},
			"Blue Whale Oil": {"rate": 10, "count": 1},
			"Advanced Alchemy Tool": {"rate": 50, "count": 1},
			"Tears of the Falling Moon": {"rate": 10, "count": 1},
			"Trace of Chaos": {"rate": 100, "count": 4},
			"Trace of the Earth": {"rate": 100, "count": 4},
			"Trace of Ascension": {"rate": 100, "count": 4},
			"Trace of Savagery": {"rate": 100, "count": 4},
			"Trace of Origin": {"rate": 100, "count": 4},
			"Trace of Battle": {"rate": 100, "count": 4},
			"Trace of Hunting": {"rate": 100, "count": 4},
			"Trace of Forest": {"rate": 100, "count": 4},
			"Trace of Violence": {"rate": 100, "count": 4},
			"Trace of Death": {"rate": 100, "count": 4},
			"Trace of Memory": {"rate": 100, "count": 4},
			"Clear Liquid Reagent": {"rate": 100, "count": 30},
			"Pure Powder Reagent": {"rate": 100, "count": 30},
		}
	},
	"[Alchemy] Special Delivery Gift Box": {
		"items": {
			"Manos Alchemist's Clothes": {"rate": 1, "count": 1},
			"Forest Fury": {"rate": 1, "count": 1},
			"Blue Whale Oil": {"rate": 10, "count": 1},
			"Blue Whale Meat": {"rate": 10, "count": 1},
			"Advanced Alchemy Tool": {"rate": 50, "count": 1},
			"Tears of the Falling Moon": {"rate": 10, "count": 2},
			"Trace of Chaos": {"rate": 100, "count": 5},
			"Trace of the Earth": {"rate": 100, "count": 5},
			"Trace of Ascension": {"rate": 100, "count": 5},
			"Trace of Savagery": {"rate": 100, "count": 5},
			"Trace of Origin": {"rate": 100, "count": 5},
			"Trace of Battle": {"rate": 100, "count": 5},
			"Trace of Hunting": {"rate": 100, "count": 5},
			"Trace of Forest": {"rate": 100, "count": 5},
			"Trace of Violence": {"rate": 100, "count": 5},
			"Trace of Death": {"rate": 100, "count": 5},
			"Trace of Memory": {"rate": 100, "count": 5},
			"Clear Liquid Reagent": {"rate": 100, "count": 40},
			"Pure Powder Reagent": {"rate": 100, "count": 40},
		}
	},
	"[Alchemy] Shiny Delivery Gift Box": {
		"items": {
			"Manos Alchemist's Clothes": {"rate": 1, "count": 1},
			"Forest Fury": {"rate": 1, "count": 1},
			"Blue Whale Oil": {"rate": 10, "count": 1},
			"Blue Whale Meat": {"rate": 10, "count": 1},
			"Advanced Alchemy Tool": {"rate": 50, "count": 1},
			"Tears of the Falling Moon": {"rate": 10, "count": 3},
			"Trace of Chaos": {"rate": 100, "count": 6},
			"Trace of the Earth": {"rate": 100, "count": 6},
			"Trace of Ascension": {"rate": 100, "count": 6},
			"Trace of Savagery": {"rate": 100, "count": 6},
			"Trace of Origin": {"rate": 100, "count": 6},
			"Trace of Battle": {"rate": 100, "count": 6},
			"Trace of Hunting": {"rate": 100, "count": 6},
			"Trace of Forest": {"rate": 100, "count": 6},
			"Trace of Violence": {"rate": 100, "count": 6},
			"Trace of Death": {"rate": 100, "count": 6},
			"Trace of Memory": {"rate": 100, "count": 6},
			"Clear Liquid Reagent": {"rate": 100, "count": 50},
			"Pure Powder Reagent": {"rate": 100, "count": 50},
		}
	},
}



