cooking = {
	"Apprentice's Cooking Box": {
		"base_value": 52000,
		"reward": "[Cooking] Small Delivery Gift Box",
		"materials": {
			"Teff Bread": 390,
			"Spongy Teff Bread": 130,
			"High-Quality Carrot Juice": 360,
			"Special Carrot Juice": 180,
			"Exotic Herbal Wine": 180,
			"Full Bodied Herbal Wine": 60,
			"Fig Pie": 60,
			"Sweet Fig Pie": 20,
			"Smoked Fish Steak": 180,
			"Golden Smoked Fish Steak": 60,
			"Fruit Juice": 60,
			"Thick Fruit Juice": 20,
			"Beer": 60,
			"Cold Draft Beer": 20,
			"Fried Fish": 90,
			"Crispy Fried Fish": 30,
			"Grain Soup": 45,
			"Special Grain Soup": 15,
			"Five-Grain Chicken Porridge": 30,
			"Thick Five-Grain Chicken Porridge": 10,
			"Boiled Bird Eggs": 30,
			"Appealing Boiled Bird Eggs": 10,
			"Seafood Mushroom Salad": 30,
			"Special Seafood Mushroom Salad": 10,
			"Aloe Cookie": 21,
			"Sweet Aloe Cookie": 7,
			"Steamed Fish": 30,
			"Lean Steamed Fish": 10,
			"Fried Vegetables": 15,
			"Crispy Fried Vegetables": 5
		}
	},
	"Skilled Cook's Cooking Box": {
		"base_value": 80000,
		"reward": "[Cooking] Plain Delivery Gift Box",
		"materials": {
			"Grilled Bird Meat": 90,
			"Steaming Hot Grilled Bird Meat": 30,
			"Pickled Fish": 120,
			"Sour Pickled Fish": 40,
			"Date Palm Wine": 60,
			"Mild Date Palm Wine": 20,
			"Honey Wine": 60,
			"Tangy Honey Wine": 20,
			"Fish Fillet Chips": 75,
			"Mouth Watering Fish Fillet Chips": 25,
			"Fruit Wine": 45,
			"Luscious Fruit Wine": 15,
			"Pistachio Fried Rice": 36,
			"Savory Pistachio Fried Rice": 12,
			"Seafood Grilled with Butter": 36,
			"Savory Seafood Grilled with Butter": 12,
			"Fish Soup": 33,
			"Special Fish Soup": 11,
			"Tea With Fine Scent": 21,
			"Tea With Strong Scent": 7,
			"Steamed Seafood": 30,
			"Plentiful Steamed Fish": 10,
			"Fruit and Vegetable Salad": 21,
			"Fresh Fruit and Vegetable Salad": 7,
			"Steamed Bird": 18,
			"Well Aged Steamed Bird": 6,
			"Seafood Pasta": 18,
			"High-Quality Seafood Pasta": 6,
			"Omelet": 18,
			"Soft Omelet": 6,
			"Stir Fried Vegetables": 18,
			"Crispy Stir Fried": 6
		}
	},
	"Professional's Cooking Box": {
		"base_value": 120000,
		"reward": "[Cooking] Resplendent Delivery Gift Box",
		"materials": {
			"Fruit Pie": 24,
			"Sweet Fruit Pie": 8,
			"Fish Fillet Salad": 24,
			"Fresh Fish Fillet Salad": 8,
			"Steamed Prawn": 24,
			"Hearty Steamed Prawn": 8,
			"Fried Bird": 24,
			"Divine Fried Bird": 8,
			"Meat Pie": 21,
			"Lean Meat Pie": 7,
			"Aloe Yogurt": 18,
			"Thick Aloe Yogurt": 6,
			"Stir-Fried Seafood": 21,
			"Special Stir-Fried Seafood": 7,
			"Desert Dumpling": 18,
			"Chewy Desert Dumpling": 6,
			"Roast Marmot": 18,
			"Golden Roast Marmot": 6,
			"Couscous": 18,
			"Classic Couscous": 6,
			"Meat Stew": 18,
			"Thick Meat Stew": 6,
			"Prawn Salad": 18,
			"Sweet and Sour Prawn Salad": 6,
			"Freekeh Snake Stew": 15,
			"Thick Freekeh Snake Stew": 5,
			"Pickled Vegetables": 18,
			"Sweet and Sour Pickled Vegetables": 6,
			"Soft Bread": 15,
			"Moist Milk Bread": 5,
			"Fruit Pudding": 15,
			"Special Fruit Pudding": 5
		}
	},
	"Artisan's Cooking Box": {
		"base_value": 160000,
		"reward": "[Cooking] Splendid Delivery Gift Box",
		"materials": {
			"Coconut Cocktail": 54,
			"Chilled Coconut Cocktail": 18,
			"Coconut Fried Fish": 36,
			"Crispy Coconut Fried Fish": 12,
			"Coconut Pasta": 21,
			"Sweet Coconut Pasta": 7,
			"Rainbow Button Mushroom Cheese Melt": 21,
			"Mild Rainbow Button Mushroom Cheese Melt": 7,
			"Teff Sandwich": 18,
			"Spicy Teff Sandwich": 6,
			"Pan-Fried Oyster": 18,
			"Aromatic Pan-Fried Oyster": 6,
			"Rainbow Button Mushroom Sandwich": 18,
			"Sweet Rainbow Button Mushroom Sandwich": 6,
			"Meat Soup": 18,
			"Special Meat Soup": 6,
			"Grilled Scorpion": 15,
			"Crispy Grilled Scorpion": 5,
			"Borscht": 15,
			"Fragrant Borscht": 5,
			"Grilled Sausage": 15,
			"Smoked Sausage": 5,
			"Cheese Pie": 15,
			"High-Quality Cheese Pie": 5,
			"Meat Pasta": 15,
			"Spaghetti Alla Bolognese": 5,
			"Lizard Kebab": 15,
			"Lean Lizard Kebab": 5,
			"Steak": 15,
			"Juicy Steak": 5,
			"Oatmeal": 15,
			"Refined Oatmeal": 5
		}
	},
	"Master's Cooking Box": {
		"base_value": 220000,
		"reward": "[Cooking] Special Delivery Gift Box",
		"materials": {
			"Assorted Side Dishes": 27,
			"Plentiful Assorted Side Dishes": 9,
			"Sute Tea": 18,
			"Healthy Sute Tea": 6,
			"Milk Tea": 18,
			"Smooth Milk Tea": 6,
			"Skewered Llama Cheese Melt": 18,
			"Spicy Skewered Llama Cheese Melt": 6,
			"Cheese Gratin": 18,
			"Chewy Cheese Gratin": 6,
			"Stir-Fried Meat": 18,
			"Special Stir-Fried Meat": 6,
			"Hunter's Salad": 18,
			"Fresh Hunter's Salad": 6,
			"Honeycomb Cookie": 18,
			"Crispy Honeycomb Cookie": 6,
			"Special Arehaza Meal": 18,
			"Lean Meat Salad": 18,
			"Top Grade Lean Meat Salad": 6,
			"Meat Croquette": 18,
			"Crispy Meat Croquette": 6,
			"Stir-Fried Bracken": 18,
			"Savory Stir-Fried Bracken": 6,
			"Dark Pudding": 15,
			"Bloody Dark Pudding": 5,
			"Ghormeh Sabzi": 15,
			"Thick Ghormeh Sabzi": 5,
			"Savory Steak": 15,
			"Balenos Meal": 15,
			"Special Balenos Meal": 5
		}
	},
	"Guru's Cooking Box": {
		"base_value": 320000,
		"reward": "[Cooking] Shiny Delivery Gift Box",
		"materials": {
			"Kamasylvia Meal": 33,
			"Special Kamasylvia Meal": 11,
			"Margoria Seafood Meal": 21,
			"Butter-Roasted Lobster": 21,
			"Golden Butter-Roasted Lobster": 7,
			"Serendia Meal": 21,
			"Special Serendia Meal": 7,
			"Valencia Meal": 18,
			"Special Valencia Meal": 6,
			"King of Jungle Hamburg": 24,
			"Jumbo King of Jungle Hamburg": 8,
			"Special Drieghanese Meal": 18,
			"Knight Combat Rarions": 18,
			"Meat Sandwich": 18,
			"High-Quality Meat Sandwich": 6,
			"Calpheon Meal": 18,
			"Special Calpheon Meal": 6,
			"Ham Sandwich": 18,
			"High-Quality Ham Sandwich": 6,
			"Mediah Meal": 15,
			"Special Mediah Meal": 5,
			"Khalk's Fermented Wine": 12,
			"Khalk's Strong Fermented Wine": 4,
			"Hard-Boiled Shellfish": 12,
			"Big Hard-Boiled Shellfish": 4
		}
	},
}